kind: pipeline
type: docker
name: test

steps:
  - name: Test Python
    image: python:3.10
    commands:
      - pip install -r requirements-test.txt
      - flake8
      - coverage run -m unittest
      - coverage report -m
